/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as PlayRouteImport } from './routes/play'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AslRouteImport } from './routes/asl'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as StudyPlannerRouteImport } from './routes/study.planner'
import { Route as StudyFlashcardsRouteImport } from './routes/study.flashcards'
import { Route as StudyDueRouteImport } from './routes/study.due'
import { Route as SettingsAccessibilityRouteImport } from './routes/settings.accessibility'
import { Route as NotesPageIdRouteImport } from './routes/notes.$pageId'
import { Route as LecturesLectureIdRouteImport } from './routes/lectures.$lectureId'
import { Route as KnowledgeAskRouteImport } from './routes/knowledge.ask'
import { Route as GameSessionIdRouteImport } from './routes/game.$sessionId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CaptureUploadRouteImport } from './routes/capture.upload'
import { Route as AssignmentsAssignmentIdRouteImport } from './routes/assignments.$assignmentId'
import { Route as StudyQuizQuizIdRouteImport } from './routes/study.quiz.$quizId'
import { Route as CoursesCourseIdSearchRouteImport } from './routes/courses.$courseId.search'
import { Route as CoursesCourseIdModulesRouteImport } from './routes/courses.$courseId.modules'
import { Route as StudyQuizQuizIdMultiplayerRouteImport } from './routes/study.quiz.$quizId.multiplayer'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AslRoute = AslRouteImport.update({
  id: '/asl',
  path: '/asl',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => TagsRoute,
} as any)
const StudyPlannerRoute = StudyPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => StudyRoute,
} as any)
const StudyFlashcardsRoute = StudyFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudyRoute,
} as any)
const StudyDueRoute = StudyDueRouteImport.update({
  id: '/due',
  path: '/due',
  getParentRoute: () => StudyRoute,
} as any)
const SettingsAccessibilityRoute = SettingsAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => SettingsRoute,
} as any)
const NotesPageIdRoute = NotesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => NotesRoute,
} as any)
const LecturesLectureIdRoute = LecturesLectureIdRouteImport.update({
  id: '/lectures/$lectureId',
  path: '/lectures/$lectureId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeAskRoute = KnowledgeAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => KnowledgeRoute,
} as any)
const GameSessionIdRoute = GameSessionIdRouteImport.update({
  id: '/game/$sessionId',
  path: '/game/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CaptureUploadRoute = CaptureUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => CaptureRoute,
} as any)
const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdRouteImport.update({
  id: '/assignments/$assignmentId',
  path: '/assignments/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyQuizQuizIdRoute = StudyQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => StudyRoute,
} as any)
const CoursesCourseIdSearchRoute = CoursesCourseIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdModulesRoute = CoursesCourseIdModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const StudyQuizQuizIdMultiplayerRoute =
  StudyQuizQuizIdMultiplayerRouteImport.update({
    id: '/multiplayer',
    path: '/multiplayer',
    getParentRoute: () => StudyQuizQuizIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/asl': typeof AslRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/decks': typeof DecksRoute
  '/export': typeof ExportRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/play': typeof PlayRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/study': typeof StudyRouteWithChildren
  '/tags': typeof TagsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/today': typeof TodayRoute
  '/trash': typeof TrashRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/capture/upload': typeof CaptureUploadRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/game/$sessionId': typeof GameSessionIdRoute
  '/knowledge/ask': typeof KnowledgeAskRoute
  '/lectures/$lectureId': typeof LecturesLectureIdRoute
  '/notes/$pageId': typeof NotesPageIdRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/study/due': typeof StudyDueRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/planner': typeof StudyPlannerRoute
  '/tags/$tag': typeof TagsTagRoute
  '/courses/$courseId/modules': typeof CoursesCourseIdModulesRoute
  '/courses/$courseId/search': typeof CoursesCourseIdSearchRoute
  '/study/quiz/$quizId': typeof StudyQuizQuizIdRouteWithChildren
  '/study/quiz/$quizId/multiplayer': typeof StudyQuizQuizIdMultiplayerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/asl': typeof AslRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/decks': typeof DecksRoute
  '/export': typeof ExportRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/play': typeof PlayRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/study': typeof StudyRouteWithChildren
  '/tags': typeof TagsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/today': typeof TodayRoute
  '/trash': typeof TrashRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/capture/upload': typeof CaptureUploadRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/game/$sessionId': typeof GameSessionIdRoute
  '/knowledge/ask': typeof KnowledgeAskRoute
  '/lectures/$lectureId': typeof LecturesLectureIdRoute
  '/notes/$pageId': typeof NotesPageIdRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/study/due': typeof StudyDueRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/planner': typeof StudyPlannerRoute
  '/tags/$tag': typeof TagsTagRoute
  '/courses/$courseId/modules': typeof CoursesCourseIdModulesRoute
  '/courses/$courseId/search': typeof CoursesCourseIdSearchRoute
  '/study/quiz/$quizId': typeof StudyQuizQuizIdRouteWithChildren
  '/study/quiz/$quizId/multiplayer': typeof StudyQuizQuizIdMultiplayerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/asl': typeof AslRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/decks': typeof DecksRoute
  '/export': typeof ExportRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/play': typeof PlayRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/study': typeof StudyRouteWithChildren
  '/tags': typeof TagsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/today': typeof TodayRoute
  '/trash': typeof TrashRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/capture/upload': typeof CaptureUploadRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/game/$sessionId': typeof GameSessionIdRoute
  '/knowledge/ask': typeof KnowledgeAskRoute
  '/lectures/$lectureId': typeof LecturesLectureIdRoute
  '/notes/$pageId': typeof NotesPageIdRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/study/due': typeof StudyDueRoute
  '/study/flashcards': typeof StudyFlashcardsRoute
  '/study/planner': typeof StudyPlannerRoute
  '/tags/$tag': typeof TagsTagRoute
  '/courses/$courseId/modules': typeof CoursesCourseIdModulesRoute
  '/courses/$courseId/search': typeof CoursesCourseIdSearchRoute
  '/study/quiz/$quizId': typeof StudyQuizQuizIdRouteWithChildren
  '/study/quiz/$quizId/multiplayer': typeof StudyQuizQuizIdMultiplayerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/asl'
    | '/calendar'
    | '/capture'
    | '/courses'
    | '/decks'
    | '/export'
    | '/knowledge'
    | '/lab'
    | '/login'
    | '/notes'
    | '/play'
    | '/sessions'
    | '/settings'
    | '/study'
    | '/tags'
    | '/templates'
    | '/today'
    | '/trash'
    | '/assignments/$assignmentId'
    | '/capture/upload'
    | '/courses/$courseId'
    | '/game/$sessionId'
    | '/knowledge/ask'
    | '/lectures/$lectureId'
    | '/notes/$pageId'
    | '/settings/accessibility'
    | '/study/due'
    | '/study/flashcards'
    | '/study/planner'
    | '/tags/$tag'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/search'
    | '/study/quiz/$quizId'
    | '/study/quiz/$quizId/multiplayer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/asl'
    | '/calendar'
    | '/capture'
    | '/courses'
    | '/decks'
    | '/export'
    | '/knowledge'
    | '/lab'
    | '/login'
    | '/notes'
    | '/play'
    | '/sessions'
    | '/settings'
    | '/study'
    | '/tags'
    | '/templates'
    | '/today'
    | '/trash'
    | '/assignments/$assignmentId'
    | '/capture/upload'
    | '/courses/$courseId'
    | '/game/$sessionId'
    | '/knowledge/ask'
    | '/lectures/$lectureId'
    | '/notes/$pageId'
    | '/settings/accessibility'
    | '/study/due'
    | '/study/flashcards'
    | '/study/planner'
    | '/tags/$tag'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/search'
    | '/study/quiz/$quizId'
    | '/study/quiz/$quizId/multiplayer'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/asl'
    | '/calendar'
    | '/capture'
    | '/courses'
    | '/decks'
    | '/export'
    | '/knowledge'
    | '/lab'
    | '/login'
    | '/notes'
    | '/play'
    | '/sessions'
    | '/settings'
    | '/study'
    | '/tags'
    | '/templates'
    | '/today'
    | '/trash'
    | '/assignments/$assignmentId'
    | '/capture/upload'
    | '/courses/$courseId'
    | '/game/$sessionId'
    | '/knowledge/ask'
    | '/lectures/$lectureId'
    | '/notes/$pageId'
    | '/settings/accessibility'
    | '/study/due'
    | '/study/flashcards'
    | '/study/planner'
    | '/tags/$tag'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/search'
    | '/study/quiz/$quizId'
    | '/study/quiz/$quizId/multiplayer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AslRoute: typeof AslRoute
  CalendarRoute: typeof CalendarRoute
  CaptureRoute: typeof CaptureRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DecksRoute: typeof DecksRoute
  ExportRoute: typeof ExportRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRouteWithChildren
  PlayRoute: typeof PlayRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StudyRoute: typeof StudyRouteWithChildren
  TagsRoute: typeof TagsRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  TodayRoute: typeof TodayRoute
  TrashRoute: typeof TrashRoute
  AssignmentsAssignmentIdRoute: typeof AssignmentsAssignmentIdRoute
  GameSessionIdRoute: typeof GameSessionIdRoute
  LecturesLectureIdRoute: typeof LecturesLectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asl': {
      id: '/asl'
      path: '/asl'
      fullPath: '/asl'
      preLoaderRoute: typeof AslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof TagsRoute
    }
    '/study/planner': {
      id: '/study/planner'
      path: '/planner'
      fullPath: '/study/planner'
      preLoaderRoute: typeof StudyPlannerRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/flashcards': {
      id: '/study/flashcards'
      path: '/flashcards'
      fullPath: '/study/flashcards'
      preLoaderRoute: typeof StudyFlashcardsRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/due': {
      id: '/study/due'
      path: '/due'
      fullPath: '/study/due'
      preLoaderRoute: typeof StudyDueRouteImport
      parentRoute: typeof StudyRoute
    }
    '/settings/accessibility': {
      id: '/settings/accessibility'
      path: '/accessibility'
      fullPath: '/settings/accessibility'
      preLoaderRoute: typeof SettingsAccessibilityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/notes/$pageId': {
      id: '/notes/$pageId'
      path: '/$pageId'
      fullPath: '/notes/$pageId'
      preLoaderRoute: typeof NotesPageIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/lectures/$lectureId': {
      id: '/lectures/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/lectures/$lectureId'
      preLoaderRoute: typeof LecturesLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/ask': {
      id: '/knowledge/ask'
      path: '/ask'
      fullPath: '/knowledge/ask'
      preLoaderRoute: typeof KnowledgeAskRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/game/$sessionId': {
      id: '/game/$sessionId'
      path: '/game/$sessionId'
      fullPath: '/game/$sessionId'
      preLoaderRoute: typeof GameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/capture/upload': {
      id: '/capture/upload'
      path: '/upload'
      fullPath: '/capture/upload'
      preLoaderRoute: typeof CaptureUploadRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/assignments/$assignmentId': {
      id: '/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/quiz/$quizId': {
      id: '/study/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/study/quiz/$quizId'
      preLoaderRoute: typeof StudyQuizQuizIdRouteImport
      parentRoute: typeof StudyRoute
    }
    '/courses/$courseId/search': {
      id: '/courses/$courseId/search'
      path: '/search'
      fullPath: '/courses/$courseId/search'
      preLoaderRoute: typeof CoursesCourseIdSearchRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/modules': {
      id: '/courses/$courseId/modules'
      path: '/modules'
      fullPath: '/courses/$courseId/modules'
      preLoaderRoute: typeof CoursesCourseIdModulesRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/study/quiz/$quizId/multiplayer': {
      id: '/study/quiz/$quizId/multiplayer'
      path: '/multiplayer'
      fullPath: '/study/quiz/$quizId/multiplayer'
      preLoaderRoute: typeof StudyQuizQuizIdMultiplayerRouteImport
      parentRoute: typeof StudyQuizQuizIdRoute
    }
  }
}

interface CaptureRouteChildren {
  CaptureUploadRoute: typeof CaptureUploadRoute
}

const CaptureRouteChildren: CaptureRouteChildren = {
  CaptureUploadRoute: CaptureUploadRoute,
}

const CaptureRouteWithChildren =
  CaptureRoute._addFileChildren(CaptureRouteChildren)

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdModulesRoute: typeof CoursesCourseIdModulesRoute
  CoursesCourseIdSearchRoute: typeof CoursesCourseIdSearchRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdModulesRoute: CoursesCourseIdModulesRoute,
  CoursesCourseIdSearchRoute: CoursesCourseIdSearchRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeAskRoute: typeof KnowledgeAskRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeAskRoute: KnowledgeAskRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface NotesRouteChildren {
  NotesPageIdRoute: typeof NotesPageIdRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesPageIdRoute: NotesPageIdRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface SettingsRouteChildren {
  SettingsAccessibilityRoute: typeof SettingsAccessibilityRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccessibilityRoute: SettingsAccessibilityRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StudyQuizQuizIdRouteChildren {
  StudyQuizQuizIdMultiplayerRoute: typeof StudyQuizQuizIdMultiplayerRoute
}

const StudyQuizQuizIdRouteChildren: StudyQuizQuizIdRouteChildren = {
  StudyQuizQuizIdMultiplayerRoute: StudyQuizQuizIdMultiplayerRoute,
}

const StudyQuizQuizIdRouteWithChildren = StudyQuizQuizIdRoute._addFileChildren(
  StudyQuizQuizIdRouteChildren,
)

interface StudyRouteChildren {
  StudyDueRoute: typeof StudyDueRoute
  StudyFlashcardsRoute: typeof StudyFlashcardsRoute
  StudyPlannerRoute: typeof StudyPlannerRoute
  StudyQuizQuizIdRoute: typeof StudyQuizQuizIdRouteWithChildren
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyDueRoute: StudyDueRoute,
  StudyFlashcardsRoute: StudyFlashcardsRoute,
  StudyPlannerRoute: StudyPlannerRoute,
  StudyQuizQuizIdRoute: StudyQuizQuizIdRouteWithChildren,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

interface TagsRouteChildren {
  TagsTagRoute: typeof TagsTagRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagRoute: TagsTagRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AslRoute: AslRoute,
  CalendarRoute: CalendarRoute,
  CaptureRoute: CaptureRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DecksRoute: DecksRoute,
  ExportRoute: ExportRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRouteWithChildren,
  PlayRoute: PlayRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StudyRoute: StudyRouteWithChildren,
  TagsRoute: TagsRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  TodayRoute: TodayRoute,
  TrashRoute: TrashRoute,
  AssignmentsAssignmentIdRoute: AssignmentsAssignmentIdRoute,
  GameSessionIdRoute: GameSessionIdRoute,
  LecturesLectureIdRoute: LecturesLectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
